name: BotanicalReplication
description: Small flowers can be replicated with bone meal like big flowers.
author: Raus
main: com.raus.botanicalReplication.Main
version: 1.0
api-version: 1.15

commands:
  botanical:
    description: Botanical replication
    default: true
    usage: "Usage: /botanical [info|reload]"

permissions:
  botanical.reload:
    default: op
    description: Allows you to reload the config